<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>ChromeDotNet_Test</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="webSources\*" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="webSources\*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LibChromeDotNet\LibChromeDotNet.csproj" />
  </ItemGroup>

</Project>
