<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>CDN_WebAppTemplate</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="web\*" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="web\*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="C:\Users\Reina\Documents\GitHub\ChromeDotNet\LibChromeDotNet\LibChromeDotNet.csproj" />
  </ItemGroup>

</Project>
