<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <RootNamespace>CDN_WebAppTemplate</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="web\*" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="web\*" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="LibChromeDotNet">
      <HintPath>LibChromeDotNet.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="LibChromeDotNet.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
